[Microsoft.Android.Build.BaseTasks] automatically report locked files
Context: https://github.com/dotnet/msbuild/commit/5f27e4d861a19ecff094161ff203a8a5924bd3d2

Since ~2017, MSBuild has added useful context to the `<Copy/>` task
that reports *which* process locks a certain file on Windows. This
logic has slowly been added to more places in MSBuild.

We should add this logic to `Microsoft.Android.Build.BaseTasks` as well!

* If an `AndroidTask` gets an `IOException`

* And we can parse a file path between the `''` characters

* And the file exists

Report an error message such as:

    error XAMYT7024: The file "D:\temp\tmphkqpda.tmp" is locked by: "MSBuild (22040)"
    System.IO.IOException: The process cannot access the file 'D:\temp\tmphkqpda.tmp' because it is being used by another process.
       at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile (String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
    ... rest of stacktrace

This requires us to bring over two files from MSBuild:

* `LockCheck.cs`
* `NativeMethodsShared.cs`

I only made a couple small changes to `LockCheck.cs`:

* Format the entire file with `dotnet-format`

* For localization, use `Resources.LockCheck_FileLocked` directly

* Change visibility of various methods

* Only `LockCheck.GetLockedFileMessage()` is public