[Microsoft.Android.Build.BaseTasks] report locked files in XA*7024 (#242)
Context: https://github.com/dotnet/msbuild/commit/5f27e4d861a19ecff094161ff203a8a5924bd3d2
Context: https://github.com/dotnet/msbuild/commit/8f2286275c24562f0b4b82cef9ff831bd10420c6

Since ~2017, MSBuild has added useful context to the `<Copy/>` task
that reports *which* process holds file locks on Windows.

This logic has slowly been added to more places in MSBuild, and
eventually became the public [`LockCheck.GetLockedFileMessage()`][0]
method in the [Microsoft.Build.Utilities.Core 17.11.4 NuGet][1].

Update `UnhandledExceptionLogger` so that when an `IOException` is
encountered, we check the `IOException.Message` text for anything
between single quotes, e.g. `'C:\this\is\a\path'`.  After extracting
any such value, *if* the value is a file, as per `File.Exists()`, we
assume that this file is the one causing a file share-related
exception, and call `LockCheck.GetLockedFileMessage(path)`.

This allows us to report an error such as:

	error XAMYT7024: The file is locked by: "MSBuild (22040)".
	System.IO.IOException: The process cannot access the file 'D:\temp\tmphkqpda.tmp' because it is being used by another process.
	   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile (String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
	   …

[0]: https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.lockcheck.getlockedfilemessage?view=msbuild-17-netcore
[1]: https://www.nuget.org/packages/Microsoft.Build.Utilities.Core/17.11.4